const Map<String, String> ar = {
  "Home": "الرئيسية",
  "Deals": "الإتفاقيات",
  "Sales": "المبيعات",
  "Statistics": "الإحصائيات",
  "Payments": "المدفوعات",
  "Settings": "الإعدادات",
  "Profile": "الملف الشخصي",
  "Notifications": "الإشعارات",
  "Help": "المساعدة",
  "Logout": "تسجيل الخروج",
  "Buyer Agreements": "اتفاقيات مشترين",
  "Farmer Agreements": "اتفاقيات مزارعين",
  "Supplies": "التوريدات",
  "Returns": "المرتجعات",
  "Select": "اختار",
  "Total Sales Amount": "إجمالي مبلغ المبيعات",
  "Total Quantity Sold": "إجمالي كمية التمور المباعة",
  "Number of Buyer Returns": "عدد مرتجعات المشترين",
  "Number of Sales": "عدد المبيعات",
  "Number of Sales Contracts": "عدد عقود المبيعات",
  "Total Returned Quantity": "إجمالي كمية المرتجعات",
  "SAR": "ريال",
  "Tons": "طن",
  "Contracts": "عقود",
  "Buyers": "المشترين",
  "Farmers": "المزارعين",
  "Procer": "الموردين",
  "Agreements": "الاتفاقيات",
  "Riyadh Dates Market": "سوق التمور بالرياض",
  "Al Ahsa Dates Market": "سوق التمور بالأحساء",
  "Rejected": "مرفوض",
  "Approved": "مقبول",
  "Start Date": "تاريخ البدء",
  "End Date": "تاريخ الانتهاء",
  "Muhammed Elsheikh": "محمد ابراهيم الشيخ",
  'Trades': "المعاملات",
  "sale_number": "رقم البيع",
  "market": "السوق",
  "sale_date": "تاريخ البيع",
  "total_quantity": "الكمية الإجمالية",
  "product_count": "عدد المنتجات",
  "seller": "البائع",
  "delivered": "تم التوصيل",
  "pending": "قيد الانتظار",
  'Log in to Seasonal Market': 'تسجيل الدخول إلى الاسواق الموسمية',
  'Email': 'البريد الإلكتروني',
  'Enter your email': 'أدخل بريدك الإلكتروني',
  'Password': 'كلمة المرور *',
  'Enter your password': 'أدخل كلمة المرور',
  'Login': 'تسجيل الدخول',
  'Create New Account?': 'إنشاء حساب جديد؟',
  "Seasonal Market": "ألاسواق الموسمية",
  "sign_up": "التسجيل",
  "identity_number": "رقم الهوية *",
  "enter_identity_number": "أدخل رقم الهوية",
  "phone_number": "رقم الهاتف *",
  "date_of_birth": "تاريخ الميلاد",
  "email": "البريد الإلكتروني",
  "enter_email": "أدخل بريدك الإلكتروني",
  "gender": "الجنس",
  "select": "اختر",
  "national_address": "العنوان الوطني",
  "enter_address": "أدخل العنوان",
  "agriculture_number": "رقم الزراعة",
  "vat_number": "رقم الضريبة",
  "enter_vat_number": "أدخل رقم الضريبة",
  "markets": "الأسواق *",
  "password": "كلمة السر *",
  "enter_password": "أدخل كلمة السر",
  "confirm_password": "تأكيد كلمة السر *",
  "reenter_password": "أعد إدخال كلمة السر",
  "continue": "استمرار",
  "Individual": "فرد",
  "Select this option if you are an individual farmer and not an establishment or organization.":
      "اختر هذا الخيار إذا كنت مزارعاً فردياً وليس منشأة أو منظمة.",
  "Establishments": "منشآت",
  "Select this option if you are a company, organization, or a non-profit entity.":
      "اختر هذا الخيار إذا كنت شركة أو منظمة أو كيان غير ربحي.",
  "Enter agricultural number": "ادخل الرقم الزراعي",
  "you need to select date": "يجب عليك اختيار التاريخ",
  "Sign Up": "إنشاء حساب",
  "Please enter your email": "يرجى إدخال بريدك الإلكتروني",
  "Please enter a valid email": "يرجى إدخال بريد إلكتروني صالح",
  "Please enter your password": "يرجى إدخال كلمة المرور",
  "Password must be at least 8 characters long, \ninclude an uppercase letter, \nnumber and special character.":
      "يجب أن تكون كلمة المرور مكونة من 8 أحرف على الأقل، \nوتتضمن حرفاً كبيراً، \nرقماً وحرفاً خاصاً.",
  "Please enter your name": "يرجى إدخال اسمك",
  "Name can only contain letters and spaces":
      "يمكن أن يحتوي الاسم على الحروف والمسافات فقط",
  "Name must be at least 2 characters long":
      "يجب أن يتكون الاسم من حرفين على الأقل",
  "Please enter a number": "يرجى إدخال رقم",
  "The input must only contain numbers": "يجب أن يحتوي الإدخال على أرقام فقط",
  "The number must be at least 2 digits long":
      "يجب أن يتكون الرقم من رقمين على الأقل",
  "Please enter your address": "يرجى إدخال عنوانك",
  "Address can only contain letters and spaces":
      "يمكن أن يحتوي العنوان على الحروف والمسافات فقط",
  "Address must be at least 2 characters long":
      "يجب أن يتكون العنوان من حرفين على الأقل",
  "Please enter your phone number": "يرجى إدخال رقم هاتفك",
  "Please enter a valid phone number": "يرجى إدخال رقم هاتف صالح",
  "Phone number must be between 8 and 15 digits":
      "يجب أن يتكون رقم الهاتف من 8 إلى 15 رقمًا",
  "Please confirm your password": "يرجى تأكيد كلمة المرور",
  "Passwords do not match": "كلمات المرور غير متطابقة",
  "Please enter your identity number": "يرجى إدخال رقم هويتك",
  "Identity number must contain only numbers":
      "يجب أن يحتوي رقم الهوية على أرقام فقط",
  "Identity number must not exceed 10 digits":
      "يجب ألا يتجاوز رقم الهوية 10 أرقام",
  "male": "ذكر",
  "female": "أنثي",
  "Elryad Market": "سوق الرياض",
  "CEntral Market": "السوق المركزي",
  "Done": "تم",
  "Cancel": "إلغاء",
};
