const Map<String, String> en = {
  "Home": "Home",
  "Deals": "Deals",
  "Sales": "Sales",
  "Statistics": "Statistics",
  "Payments": "Payments",
  "Settings": "Settings",
  "Profile": "Profile",
  "Notifications": "Notifications",
  "Help": "Help",
  "Logout": "Logout",
  "Buyer Agreements": "Buyer Agreements",
  "Farmer Agreements": "Farmer Agreements",
  "Supplies": "Supplies",
  "Returns": "Returns",
  "Total Sales Amount": "Total Sales Amount",
  "Total Quantity Sold": "Total Quantity Sold",
  "Number of Buyer Returns": "Number of Buyer Returns",
  "Number of Sales": "Number of Sales",
  "Number of Sales Contracts": "Number of Sales Contracts",
  "Total Returned Quantity": "Total Returned Quantity",
  "SAR": "SAR",
  "Tons": "Tons",
  "Contracts": "Contracts",
  "Buyers": "Buyers",
  "Farmers": "Farmers",
  "Procer": "Procer",
  "Select": "select",
  "Agreements": "Agreements",
  "Riyadh Dates Market": "Riyadh Dates Market",
  "Al Ahsa Dates Market": "Al Ahsa Dates Market",
  "Rejected": "Rejected",
  "Approved": "Approved",
  "Start Date": "Start Date",
  "End Date": "End Date",
  "Muhammed Elsheikh": "محمد الشيخ",
  'Trades':"Trades",
  "sale_number": "Sale Number",
  "market": "Market",
  "sale_date": "Sale Date",
  "total_quantity": "Total Quantity",
  "product_count": "Product Count",
  "seller": "Seller",
  "delivered": "Delivered",
  "pending": "Pending",
  'Log in to Seasonal Market': 'Log in to Seasonal Market',
  'Email': 'Email',
  'Enter your email': 'Enter your email',
  'Password': 'Password',
  'Enter your password': 'Enter your password',
  'Login': 'Login',
  'Create New Account?': 'Create New Account?',
  "Seasonal Market":"Seasonal Market",
  'sign_up': 'Sign Up',
  'identity_number': 'Identity Number',
  'enter_identity_number': 'Enter your Identity Number',
  'phone_number': 'Phone number',
  'date_of_birth': 'Date of Birth',
  'email': 'Email',
  'enter_email': 'Enter your email',
  'gender': 'Gender',
  'select': 'Select',
  'national_address': 'National Address',
  'enter_address': 'Enter address',
  'agriculture_number': 'Agricultural number',
  'vat_number': 'Vat Number',
  'enter_vat_number': 'Enter vat number',
  'markets': 'Markets',
  'password': 'Password',
  'enter_password': 'Enter your password',
  'confirm_password': 'Confirm Password',
  'reenter_password': 'Re-enter password',
  'continue': 'Continue',
  "Individual":"Individual",
  "Select this option if you are an individual farmer and not an establishment or organization.":"",
  "Establishments":"",
  "Select this option if you are a company, organization, or a non-profit entity.":"",
  "Enter agricultural number":"Enter agricultural number",
  "Sign Up":"Sign Up",
  "Please enter your email": "Please enter your email",
  "Please enter a valid email": "Please enter a valid email",
  "Please enter your password": "Please enter your password",
  "Password must be at least 8 characters long, \ninclude an uppercase letter, \nnumber and special character.": "Password must be at least 8 characters long, \ninclude an uppercase letter, \nnumber and special character.",
  "Please enter your name": "Please enter your name",
  "Name can only contain letters and spaces": "Name can only contain letters and spaces",
  "Name must be at least 2 characters long": "Name must be at least 2 characters long",
  "Please enter a number": "Please enter a number",
  "The input must only contain numbers": "The input must only contain numbers",
  "The number must be at least 2 digits long": "The number must be at least 2 digits long",
  "Please enter your address": "Please enter your address",
  "Address can only contain letters and spaces": "Address can only contain letters and spaces",
  "Address must be at least 2 characters long": "Address must be at least 2 characters long",
  "Please enter your phone number": "Please enter your phone number",
  "Please enter a valid phone number": "Please enter a valid phone number",
  "Phone number must be between 8 and 15 digits": "Phone number must be between 8 and 15 digits",
  "Please confirm your password": "Please confirm your password",
  "Passwords do not match": "Passwords do not match",
  "Please enter your identity number": "Please enter your identity number",
  "Identity number must contain only numbers": "Identity number must contain only numbers",
  "Identity number must not exceed 10 digits": "Identity number must not exceed 10 digits",
  "male":"male",
  "female":"female",
  "Elryad Market":"Elryad Market",
  "CEntral Market":"CEntral Market",
  "":"",
};
